insert into Diablo2API.dbo.Classes (Name, Description, Strength, Dexterity, Vitality, Energy, HealthPerVitalityPoint, StaminaPerVitalityPoint, ManaPerEnergyPoint) 
values 
('Necromancer',
'From the steamy recesses of the southern swamps comes a figure cloaked in mystery. The Necromancer, as his name implies, is an unseemly form of sorcerer whose spells deal with the raising of the dead and the summoning and control of various creatures for his purposes. Though his goals are often aligned with those of the forces of Light, some do not think that these ends can justify his foul means. Long hours of study in dank mausolea have made his skin pale and corpselike, his figure, skeletal. Most people shun him for his peculiar looks and ways, but none doubt the power of the Necromancer, for it is the stuff of nightmares.',
15,
25,
15,
25,
1.5,
1.0,
2.0),
('Amazon',
'This powerful woman warrior belongs to nomadic bands who roam the plains near the South Sea. The wandering of these groups often brings them into conflict with other peoples, so the Amazon is accustomed to fighting to defend her own. This lifestyle has made her fiercely independent and able to weather severe hardship and travel. While her skill with the bow rivals that of the Rogues, the Amazon is also adept in the use of spears and other throwing weapons, as well as in hand to hand combat. The Amazon is much sought after as a mercenary, in which type of service she will be loyal as long as her own ends are also served.',
20,
25,
20,
15,
2.0,
1.0,
1.5),
('Barbarian',
'The Barbarian, a member of any of several tribes on the fringes of civilization, rebuffs the influence of those he sees as soft and weak. Ceaseless clan warfare and the constant struggle to survive in the hostile wilderness are evident in the Barbarians sturdy and powerful frame. Though perhaps lacking the sophistication of his civilized contemporaries, the Barbarian has an acute awareness of his surroundings. Because of his shamanistic belief in the animal powers with whom he identifies, the Barbarian is sometimes associated with stories of lycanthropy. In fact, he believes that he can improve his superb battle tactics by calling upon the totemic animal spirits to infuse him with supernormal strengths and abilities.',
30,
20,
25,
10,
2.0,
1.0,
1.0),
('Assassin',
'The Assassins are an ancient order originally founded by the Vizjerei to hunt down and eliminate rogue mages within their own ranks. Employing secret disciplines to combat and resist the magical abilities of their elusive quarry, the Assassins bag of tricks includes traps and other infernal devices, martial arts, and powerful mental abilities. Common people know nothing of the Assassins, but they are widely feared and respected by all who employ the magic arts.',
20,
20,
20,
25,
2.0,
1.25,
1.5),
('Sorceress',
'A rebellious woman who has wrested the secrets of magic use from the male dominated Mage-Clans of the East, the Sorceress is an expert in mystical creation ex nihilo. Though somewhat lacking in the skills of hand-to-hand combat, she compensates for this weakness with fierce combative magic for both offense and defense. Solitary and reclusive, the Sorceress acts based on motives and ethics inscrutable to most, and sometimes seems capricious and even spiteful. In reality, she understands the struggle between Order and Chaos all too clearly, as well as her role as a warrior in this battle.',
10,
25,
10,
35,
1.0,
1.0,
2.0),
('Druid',
'The Druids are a race of nomadic warrior-poet-kings. Driven from their homelands long ago by their Barbarian brothers, the Druid tribes live primarily in the northern forests. Using mystic secrets passed down through the generations, they summon the elements of fire and wind to do their bidding, and command the creatures of the forest to aid them in battle. Shifting from their human forms into that of wild beasts, gives them abilities far beyond those of other mortals.',
15,
20,
25,
20,
1.5,
1.0,
1.0),
('Paladin',
'The Knights of Westmarch who felled the armies of mighty Leoric are pure at heart and closely follow the teachings of Zakarum, the Religion of the Light. A battle-ready warrior for whom faith is a shield, the Paladin fights for what he believes to be right. His steadfastness gives him powers to bestow blessings to his friends and wreak cruel justice on foes. There are those who call the Paladin an overwrought zealot, but others recognize in him the strength and goodness of the Light.',
25,
20,
25,
15,
2.0,
1.0,
1.5);