insert into [Diablo2API].[dbo].[Skills] 
([SkillTreeId],[Name],[Description],[PassiveEffect],[RequiredLevel]) 
values 
(3, 'Raise Skeleton', 'Early on, Necromancers learn to control the skeletal remains of deceased creatures. Invoking this skill causes a nightmarish jumble of animated bones to rise from a fresh corpse. Animated partially through their own will and partially through the summoned spirits of ancient warriors, Necromancers often maintain a small host of these reanimated soldiers to do their bidding.','', 1),
(3, 'Skeleton Mastery', 'As the Necromancer''s knowledge of the undead improves, he is able to harness and divert more powerful spirits to inhabit the corpses of the recently dead. A Necromancer who possesses this skill is able to raise skeletons and skeletal mages of a much more powerful variety.', 'Passive Effect: Improves the quality of your raised Skeletons, Magi, and Revived.', 1),
(3, 'Clay Golem', 'While it is fairly simple for a Necromancer to animate dead tissue, it is another matter entirely to instill the spark of life into inanimate objects. The Clay Golem is the simplest form of this complex art, creating a servant directly from the earth to serve the Necromancer. The intense drain this places on the psyche of the caster only allows him to maintain a single Golem of any type at a time.', '', 6),
(3, 'Golem Mastery', 'Developing this skill permits the Necromancer to divert more of his will and energies into his artificial creations. This allows the Necromancer to create more robust golems and control them with greater finesse.', 'Passive Effect: Enhances speed and life of Golems.', 12),
(3, 'Skeletal Mage', 'Dead warriors are not the only heroes that a Necromancer may summon to inhabit his creations. Many a Necromancer regales in raising the corpses of long dead wizards and bending them to his will. The priests of Rathma feel that this is the proof of the dominance of their particular branch of the mystic arts.', '', 12),
(3, 'Blood Golem', 'Utilizing a small quantity of his own blood, the Necromancer is able to give life to a creature neither living nor dead, yet formed of human tissue. This homunculus gains nourishment from the fresh blood of its slain enemies, from which it replenishes its strength.', '', 18),
(3, 'Summon Resist', 'Powerful heat, freezing cold and intense electrical attacks can take a serious toll on the bound servants of any Necromancer. By developing this skill, a Necromancer can permeate his summoned minions with a protective energy that strengthens their protection to the natural and mystical elements alike.', 'Passive Effect: Raises elemental resistances of your Minions.', 24),
(3, 'Iron Golem', 'While many mages spend their lives devoted to studying the transmutation of base metals into gold, the Necromancers have always had a somewhat different approach to transforming metals. Through complicated arcane rituals and great mental concentration, a Necromancer can summon forth a Golem from common base metals. The construct takes on the properties of the original source material, including any magical effects or other properties the original metal might have possessed.', '', 24),
(3, 'Fire Golem', 'It is believed that all life was forged when fire, earth, iron and flesh were combined. A Necromancer learned in this art can summon a Golem constructed entirely from living flame. The Necromancer summons the Golem through accelerating particles of the air at an ever increasing pace. These particles then ignite and the Golem crackles into existence, seemingly out of thin air.', '', 30),
(3, 'Revive', 'The ultimate goal of a Priest of Rathma is the perfect reanimation and control of a dead creature, maintaining the purity and properties of its body while releasing its soul to allow the Necromancer full control. When a Necromancer at long last gains this ability, he can truly claim mastery of the Great Cycle of Being.', '', 30);
